### ISSUE TITLE
A proposal for speedups

### ISSUE THREAD

**Issue by DNF2** [andrewcooke/StatefulIterators.jl#1]
I have made a gist that seems to demonstrate some substantial speed-up in some cases. I have dispensed with having several leaftypes, instead using only one parameterized type. I hope I have not misunderstood how this is supposed to work.

[Edit: The code in the gist also solves this error, since it knows the type of the underlying elements:
    ERROR: MethodError: `*` has no method matching *(::Type{UInt8})
    Closest candidates are:
      *(::Any, ::Any, ::Any, ::Any...)
     in read at .../Julia/StatefulIterators.jl/src/StatefulIterators.jl:54]

The gist is here: ~~https://gist.github.com/2d098eeefb6c00dd80fe.git~~ https://gist.github.com/okvs/2d098eeefb6c00dd80fe
Below are some tests. (I have removed the warm-up runs.)

```
julia> s = StatefulIterators.StatefulIterator(randstring(10_000_000));

julia> @time (for _ in 1:10_000_000 read(s); end)
  7.776472 seconds (90.00 M allocations: 2.086 GB, 3.50% gc time)

julia> s = StatefulIterators.StatefulIterator(randstring(10_000_000));

julia> @time read(s, 10_000_000);
 15.696537 seconds (120.00 M allocations: 2.957 GB, 11.30% gc time)
```

Note the underscore for the alternative version of StatefulIterators.

```
julia> s = StatefulIterators_.StatefulIterator(randstring(10_000_000));

julia> @time (for _ in 1:10_000_000 read(s_); end)
  0.178535 seconds

julia> StatefulIterators_.reset!(s_); 

julia> @time read(s_, 10_000_000);
  0.030358 seconds (8 allocations: 38.147 MB, 4.80% gc time)
```

Numerical arrays seem faster for reductions, but roughly the same for maps.

```
julia> r = rand(10_000_000);

julia> s = StatefulIterators.StatefulIterator(r);

julia> s_ = StatefulIterators_.StatefulIterator(r);

julia> @time sum(s)
  1.330811 seconds (40.00 M allocations: 610.344 MB, 2.51% gc time)
5.00072201357198e6

julia> @time sum(s_)
  0.024182 seconds (5 allocations: 176 bytes)
5.00072201357198e6
```

Collecting is also quite efficient

```
julia> r = rand(10_000_000);

julia> @time sa = collect(s);
  1.796479 seconds (30.00 M allocations: 586.757 MB, 34.39% gc time)

julia> @time sa_ = collect(s_);
  0.119020 seconds (40 allocations: 129.001 MB)

julia> sa == sa_
true
```

And even moreso for non-arrays:

```
julia> r = randstring(10_000_000);

julia> s = StatefulIterators.StatefulIterator(r);

julia> s_ = StatefulIterators_.StatefulIterator(r);

julia> @time sa = collect(s);
  9.112218 seconds (90.00 M allocations: 2.212 GB, 17.71% gc time)

julia> @time sa_ = collect(s_);
  0.106539 seconds (39 allocations: 65.001 MB)

julia> sa == sa_
true
```

**Comment by andrewcooke** [comment]
hi, this sounds great but (1) i can't see the gist and (2) could it still support peek() and available() for array types?  thanks!

**Comment by DNF2** [comment]
1) There is something very odd about the gist link. Perhaps I messed it up. Can you try: https://gist.github.com/okvs/2d098eeefb6c00dd80fe    ?
If this fails, I can paste the code straight into this issue (it's ~70 loc).

2) It does support `peek`, for all types I have tested. I'm not familiar with `available`. I couldn't see that in your code.

**Comment by DNF2** [comment]
I've now corrected the link to the gist.

**Comment by andrewcooke** [comment]
oh, that link works fine.

i may not have pused the code with available (i had no idea anyone else was using the package to be honest).

available gives the number of bytes left to read.  i guess really it should take a type argument.

anyway, thanks for this and i'll try look at it some time this week (i work alternate weeks, and am working this week, which is why i can't promise anything immediately).

cheers,
andrew

**Comment by DNF2** [comment]
No problem. I'm just learning Julia, and need some actual problems to work on. This was somehow both intriguing and just the right size challenge. I also see some potential uses for it, but there is no hurry on my part.

I may add `available` to the gist. It's the number of bytes left, you say, not the number of elements?

**Comment by andrewcooke** [comment]
On Mon, Nov 16, 2015 at 04:44:02AM -0800, okvs wrote:

> No problem. I'm just learning Julia, and need some actual problems to work on. This was somehow both intriguing and just the right size challenge. I also see some potential uses for it, but there is no hurry on my part.
> 
> I may add `available` to the gist. It's the number of bytes left, you say, not the number of elements?

that's a good question.  to answer it i need to understand how you can
have a typed StatefulIterator for all types.  what if it's constructed
with something that has no type (for example, a task).

the reason i had leaf types in the original code is because we know
the type of arrays, so they can be special cased with a type.

anyway, depending on the answer to the above, i guess available()
should be something like the number of the parameterised type and
available(T) should be the number of type T.

but relly i am working right now and don't have much time to think.
i'll look again later today or later this week.

sorry,
andrew

**Comment by DNF2** [comment]
There are probably many things I have not thought about, and I'm not sure it will handle all types of iterators. It look good with arrays, strings, and dicts so far. Sets as, well, I think.

As I said, there is no hurry, don't worry about it. If you come up with a difficult example, just post it at your leisure, and I'd be happy to dig into it.

**Comment by DNF2** [comment]
Updated the gist with an `available` method.

**Comment by andrewcooke** [comment]
hi,

i'm reading your code at the moment and playing around (work is done
and partner not yet home).  i like it a lot (the peek is better (but
see below) than mine, i didn't know about eltype, and i like the extra
methods).  however, it won't work with all iterables.

the most pathological iterable i know (i didn't realise how weird it
was until just now) is a task.  look at this(!):

julia> function foo()
         for i in 1:4
           produce(i)
         end
       end
foo (generic function with 1 method)

julia> t = Task(foo)
Task (runnable) @0x00007f91afd20330

julia> typeof(start(t))
Void

julia> next(t, nothing)
(nothing,nothing)

julia> t = Task(foo)
Task (runnable) @0x00007f91afd204c0

julia> done(t, nothing)
false

julia> next(t, nothing)
(1,nothing)

julia> next(t, nothing)
(1,nothing)

julia> next(t, nothing)
(1,nothing)

julia> done(t, nothing)
false

julia> next(t, nothing)
(2,nothing)

julia> done(t, nothing)
false

julia> next(t, nothing)
(3,nothing)

julia> done(t, nothing)
false

julia> next(t, nothing)
(4,nothing)

julia> done(t, nothing)
true

not sure how clear that is, but:
 1 - the state is not an Int (is a Void and isn't really used)
 2 - done() must be called before next and "enables" a single call

that breaks (1) your types and (2) your peek method.

so my thinking at the moment is that i still need two leaf types, but
that i can use your approach instead of the array type, and use a lot
of your ideas.

one thing that i feel bad about is that your code is a gist, not a
patch, so you won't appear as a github contributor if i use your
ideas.  do you know a way around this while using gists?  if not, do
you want to submit your code as a patch and then i'll merge everything
into what i see as a good solution?  we can iterate with more patches
if necessary.

cheers,
andrew

**Comment by DNF2** [comment]
I am not very familiar with tasks, so I do not immediately see a way around it.

Also, I just realized that `available` fails for `StepRange`s since `state` can be greater than the length of the iterable, yielding negative values.

Specifying `state` as an `::Int` was one of the things that speeded up the code originally, so I'm curious how efficient it will be without this.

As for submitting a patch, that is not something I've done before, so I'll have to look into it first. If it could wait until sometime tomorrow, I'll try it out. It's not a big deal, though.

**Comment by andrewcooke** [comment]
ok - i'll wait.  the reason to have two leaf types is to keep the speed of the int where we can.  andrew

**Comment by DNF2** [comment]
I updated the gist so it no longer relies on `state` being an `Int`, instead taking you original idea of using the iterator itself as the second input to `next`, and without losing much (or any) performance. Though I find my microbenchmarks oddly variable. Allocations and memory usage stays put, which is a good sign I think.

I haven't looked into tasks, so I don't really know whether or how this works, but having `Void` as state shouldn't be a problem at least. I don't know what happens to the `peek` method.

`available` is still broken for `StepRange`s.

**Comment by andrewcooke** [comment]
just to be clear:

1 - i'm not expecting you to fix everything, i can do that.

2 - i understood you'll make a patch.  so if you want me to just run
    with the gist, please say.

cheers,
andrew

**Comment by DNF2** [comment]
Hi. Sorry about not submitting a patch today like I said I would. Had to work late. 

I have a few new ideas I've put in my code (but not the gist yet). I'd like to make pull request, but it's just too late over here now (a patch == pull request, right?)

**Comment by andrewcooke** [comment]
that's ok - no rush (i am working all week so while i might do this on
an evening i have other things to do, like eat and read :)

**Comment by DNF2** [comment]
I have opened a pull request. It's my first ever, I just hope I did it correctly.

The implementation uses only one parameterized type. It seems a bit cleaner to me, and I don't think it's any less flexible. The performance is much improved over `IterIterator`.

Compared to `ArrayIterator` the latter is somewhat faster when using direct indexing, but is quite a bit slower than the new type when relying on the iterator protocol, probably due to type instability. If you look at the performance tests you will see that reading (and reinterpreting) a chunk is faster with `ArrayIterator` since it just indexes, while `collect` and `sum` are >10x faster with the new type.

I have a suspicion that the iteration can go faster. There is some extra memory usage going on after moving away from using `state::Int`. Strangely, when I had `state::Int` the generated native code for a `for` loop was virtually identical to the code for a `for` loop over the _underlying_ iterator, and yet it was 2-4x slower.

**Comment by andrewcooke** [comment]
hi - what's this Base.Take thing for in eltype?

**Comment by DNF2** [comment]
`Base.Take` is the return type from the `take` function. I noticed you used `collect(take())` for reading. Perhaps this code fragment is vestigial now, or perhaps it is somehow useful for the `collect` function, I'm not sure.

**Comment by andrewcooke** [comment]
interesting.  it's an iter whose state is not a simple integer, so i suspect it's from back when that type was fixed.  doesn't seem to be needed with your fully parameterised version.

**Comment by andrewcooke** [comment]
ok, i just pushed some work that is still incomplete (see below), but integrates many of your ideas.

some notes on this:

1 - i learnt a lot here - this was useful for me.  thanks!

2 - for some reason you're not listed as a project contributor, even though i merged the patch.  i'm sorry - i don't understand fully how github works.  i've added a credits section to the front page docs crediting you.

3 - although i've rewritten almost everything, i've kept your data structure, your main loop (with only 13 allocations!) and various other ideas.

4 - i've changed some logic.  in particular, i think available returns the number of eltype(T) instances (rather than bytes).  i plan to document why in the main page (see todo below).  i've also changed how the optimised methods are called (no longer using `@generated` which was one of the things i learnt about).  also, i prefer to test on T rather than S - i think that makes the code more understandable.

5 - i've renamed some things like reset! (good idea) to seekstart and added more methods that mirror streams.

6 - in one or two places i throw an exception rather than return nothing to avoid confusion with collections of nothing and/or to match the stream api.

things i still have to do that might explain some of the changes:

1 - better docs.  in particular, explain how these are typed streams, and how the behaviour depends on whether there's a bits type, whether they are linearly indexed, and whether the state is explicit.

2 - LinearIndexed type alias in code (that Union of arrays etc)

3 - more methods like readbytes

4 - optimized seek etc.

thanks again.  i think this is a much better library now.

**Comment by andrewcooke** [comment]
updated docs.  still need to add back performance tests and check those, but most work done.
